# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Saadi Guides

# uncomment the below when running locally from inside a docker
#repository: saadiguide/saadiguide.github.io

email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Saadi or saada is an urdu word meaning plain and simple.
  This site is meant to describe things in a simple way 
  so that others could benefit from that.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: saadiguides
github_username:  saadiguide

# Build settings
markdown: kramdown
theme: minima

#To use themes provided by others
#remote_theme: alshedivat/al-folio
#remote_theme: jekyll/minima
#remote_theme: kitian616/jekyll-TeXt-theme


plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
